apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-serving
  namespace: shared-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  template:
    metadata:
      name: demo-serving-{{name}}
    spec:
      destination:
        namespace: demo-serving
        server: "{{server}}"
      project: default
      source:
        path: gitops/shared/demo-apps/serving-demo
        repoURL: 'https://github.com/shirodkar/serverless-demo.git'
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true