kind: Service
apiVersion: v1
metadata:
  name: code-with-camel
  labels:
    app: code-with-camel
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
  selector:
    app: code-with-camel
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    template: postgresql-ephemeral-template
    template.openshift.io/template-instance-owner: ccdffa3d-f3e4-4b4e-a322-ed669de8a866
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    name: postgres
