kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: code-with-camel
  labels:
    app: code-with-camel
spec:
  to:
    kind: Service
    name: code-with-camel
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None