apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: managed-{{name}}
    spec:
      destination:
        server: "{{server}}"
      project: default
      source:
        path: gitops/platform/platform-manifests/managed
        repoURL: 'https://github.com/shirodkar/serverless-demo.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: managedservername
              value: '{{name}}'
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true