apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-managed-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: infra-{{name}}
    spec:
      destination:
        server: "{{server}}"
      project: default
      sources:
        - path: gitops/platform/platform-apps/infra
          repoURL: 'https://github.com/shirodkar/serverless-demo.git'
          targetRevision: HEAD
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true