apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/platform/infra
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recursive: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true