apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-functions
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-functions
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/demo-apps/functions-demo/manifests
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true