apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: shared-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: dev-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: apps-{{name}}
    spec:
      destination:
        server: "{{server}}"
      project: default
      source:
        path: gitops/shared/argo-apps
        repoURL: 'https://github.com/shirodkar/serverless-demo.git'
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        automated:
          enabled: true
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true