apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/platform/acm
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/platform/infra
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-eventing
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-eventing
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/apps/eventing-demo
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-serving
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-serving
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/apps/serving-demo
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-progressive-delivery
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-progressive-delivery
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/apps/progressive-delivery-demo
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-functions
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-functions
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/apps/functions-demo
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-workflow
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-workflow
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/apps/workflow-demo
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-camel
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-camel
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/apps/camel-demo
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-keda
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: demo-keda
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/apps/keda-demo
    repoURL: 'https://github.com/shirodkar/serverless-demo.git'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true